const menuTree = [
  {
    "id": "1696363115620352001",
    "parentId": "-1",
    "weight": 1,
    "name": "数字学习",
    "path": "/study",
    "keepAlive": "0",
    "onlineFlowEntryId": null,
    "onlineFormId": null,
    "sortOrder": 1,
    "icon": "icon-guanwangfangwen",
    "menuType": "0",
    "permission": null,
    "label": "数字学习",
    "children": [
      {
        "id": "1696363815100235778",
        "parentId": "1696363115620352001",
        "weight": 1,
        "name": "课程学习",
        "path": "/study/courseStudy",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 1,
        "icon": "icon-guanwangfangwen",
        "menuType": "0",
        "permission": null,
        "label": "课程学习"
      },
      {
        "id": "1696363991776903169",
        "parentId": "1696363115620352001",
        "weight": 2,
        "name": "学习地图",
        "path": "/study/studyMap",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 2,
        "icon": "icon-zhexiantu",
        "menuType": "0",
        "permission": null,
        "label": "学习地图"
      },
      {
        "id": "1696364744256012290",
        "parentId": "1696363115620352001",
        "weight": 3,
        "name": "考试广场",
        "path": "/study/examList",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 3,
        "icon": "icon-miyue",
        "menuType": "0",
        "permission": null,
        "label": "考试广场"
      },
      {
        "id": "1696364987114602497",
        "parentId": "1696363115620352001",
        "weight": 4,
        "name": "我的报名",
        "path": "/study/myEnroll",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 4,
        "icon": "icon-shouji",
        "menuType": "0",
        "permission": null,
        "label": "我的报名"
      },
      {
        "id": "1696365130706599938",
        "parentId": "1696363115620352001",
        "weight": 5,
        "name": "课程库",
        "path": "/study/courseLibrary",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 5,
        "icon": "icon-msnui-supervise",
        "menuType": "0",
        "permission": null,
        "label": "课程库"
      },
      {
        "id": "1696365311464325122",
        "parentId": "1696363115620352001",
        "weight": 6,
        "name": "线下培训",
        "path": "/study/offlineTraining",
        "keepAlive": "0",
        "onlineFlowEntryId": null,
        "onlineFormId": null,
        "sortOrder": 6,
        "icon": "icon-caidanguanli",
        "menuType": "0",
        "permission": null,
        "label": "线下培训"
      }
    ]
  },
  {
    "id": "1696363244825886722",
    "parentId": "-1",
    "weight": 2,
    "name": "数字大脑",
    "path": "/brain",
    "keepAlive": "0",
    "onlineFlowEntryId": null,
    "onlineFormId": null,
    "sortOrder": 2,
    "icon": "icon-gtsquanjushiwufuwuGTS",
    "menuType": "0",
    "permission": null,
    "label": "数字大脑"
  },
  {
    "id": "1696363348538441729",
    "parentId": "-1",
    "weight": 3,
    "name": "数字运营",
    "path": "/operation",
    "keepAlive": "0",
    "onlineFlowEntryId": null,
    "onlineFormId": null,
    "sortOrder": 3,
    "icon": "icon-bangzhushouji",
    "menuType": "0",
    "permission": null,
    "label": "数字运营"
  },
  {
    "id": "1696363433791864833",
    "parentId": "-1",
    "weight": 4,
    "name": "数字评价",
    "path": "/evaluation",
    "keepAlive": "0",
    "onlineFlowEntryId": null,
    "onlineFormId": null,
    "sortOrder": 4,
    "icon": "icon-xiaoxiguanli",
    "menuType": "0",
    "permission": null,
    "label": "数字评价"
  },
  {
    "id": "1696363614948048898",
    "parentId": "-1",
    "weight": 5,
    "name": "数字实训",
    "path": "/training",
    "keepAlive": "0",
    "onlineFlowEntryId": null,
    "onlineFormId": null,
    "sortOrder": 5,
    "icon": "icon-sucaisads",
    "menuType": "0",
    "permission": null,
    "label": "数字实训"
  }
]